name: Build and Push Image to ECR

on:
  push:
    branches:
      - main

jobs:

  build:

    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}


      - name: Get Latest Image Tag
        id: get_tag
        run: |

          REPO=${{ secrets.ECR_REPOSITORY }}
          REGION=${{ secrets.AWS_REGION }}

          echo "Fetching latest image tag..."

          LATEST_TAG=$(aws ecr describe-images \
            --repository-name $REPO \
            --region $REGION \
            --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
            --output text)

          echo "Latest tag: $LATEST_TAG"

          if [[ "$LATEST_TAG" == "None" ]]; then
            NEW_TAG="0.0.0.1"
          else
            VERSION=$(echo $LATEST_TAG | awk -F. '{print $4+1}')
            NEW_TAG="0.0.0.$VERSION"
          fi

          echo "New tag: $NEW_TAG"

          echo "IMAGE_TAG=$NEW_TAG" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} .


      - name: Push Image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
